// src/constants/menuData.js

export const menuData = [
  {
    id: 1,
    title: "Starters",
    key: "starterDishes",
    icon: "Soup",
    description: "Begin every celebration with delicious appetizers crafted to awaken every guest's appetite.",
    dishes: [
      {
        id: "s1",
        name: "Paneer Tikka",
        slug: "paneer-tikka",
        image: "/images/menu/starters/paneer-tikka.png",
        badge: "Chef's Choice",
        diet: "Veg",
        spiceLevel: 2,
        featured: true,
        popular: true,
        rating: 4.8,
        description: "Smoky grilled paneer cubes marinated with yogurt and aromatic Indian spices."
      },
      {
        id: "s2",
        name: "Hara Bhara Kabab",
        slug: "hara-bhara-kabab",
        image: "/images/menu/starters/hara-bhara-kabab.png",
        badge: "Classic",
        diet: "Veg",
        spiceLevel: 1,
        featured: false,
        popular: true,
        rating: 4.7,
        description: "Spinach, peas and potato patties crisp-fried and served alongside fresh mint chutney."
      },
      {
        id: "s3",
        name: "Crispy Spring Roll",
        slug: "crispy-spring-roll",
        image: "/images/menu/starters/spring-roll.png",
        badge: "Crispy",
        diet: "Veg",
        spiceLevel: 1,
        featured: false,
        popular: false,
        rating: 4.6,
        description: "Golden crackling rolls stuffed with julienned garden vegetables and glass noodles."
      },
      {
        id: "s4",
        name: "Veg Manchurian",
        slug: "veg-manchurian",
        image: "/images/menu/starters/veg-manchurian.png",
        badge: "Popular",
        diet: "Veg",
        spiceLevel: 2,
        featured: false,
        popular: true,
        rating: 4.7,
        description: "Savory vegetable dumplings tossed in a tangy, glossy Indo-Chinese garlic sauce."
      },
      {
        id: "s5",
        name: "Chilli Paneer",
        slug: "chilli-paneer",
        image: "/images/menu/starters/chilli-paneer.png",
        badge: "Spicy Favorite",
        diet: "Veg",
        spiceLevel: 3,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Crispy fried paneer tossed with bell peppers, onions, and hot soy-chilli glaze."
      },
      {
        id: "s6",
        name: "Corn Cheese Balls",
        slug: "corn-cheese-balls",
        image: "/images/menu/starters/corn-cheese-balls.png",
        badge: "Kids Favorite",
        diet: "Veg",
        spiceLevel: 1,
        featured: false,
        popular: false,
        rating: 4.5,
        description: "Golden crunchy exterior packed with sweet corn and gooey melted mozzarella cheese."
      },
      {
        id: "s7",
        name: "Mushroom Tikka",
        slug: "mushroom-tikka",
        image: "/images/menu/starters/mushroom-tikka.png",
        badge: "Tandoori Special",
        diet: "Veg",
        spiceLevel: 2,
        featured: false,
        popular: false,
        rating: 4.8,
        description: "Fresh button mushrooms stuffed with spiced paneer and charred to perfection in the tandoor."
      }
    ]
  },
  {
    id: 2,
    title: "Main Course",
    key: "mainCourseDishes",
    icon: "Utensils",
    description: "Rich curries, fresh tandoori breads, and fragrant rice dishes.",
    dishes: [
      // Gravies & Curries
      {
        id: "m1",
        name: "Butter Paneer",
        slug: "butter-paneer",
        category: "Curry",
        image: "/images/menu/main/butter-paneer.png",
        badge: "Best Seller",
        diet: "Veg",
        spiceLevel: 1,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Velvety, rich tomato and cashew gravy folded with pillowy soft paneer chunks."
      },
      {
        id: "m2",
        name: "Dal Makhani",
        slug: "dal-makhani",
        category: "Curry",
        image: "/images/menu/main/dal-makhani.png",
        badge: "Premium",
        diet: "Veg",
        spiceLevel: 1,
        featured: true,
        popular: true,
        rating: 4.8,
        description: "Slow-cooked black lentils simmered overnight over clay tandoors with butter and cream."
      },
      {
        id: "m3",
        name: "Kadai Paneer",
        slug: "kadai-paneer",
        category: "Curry",
        image: "/images/menu/main/kadai-paneer.png",
        badge: "Spicy",
        diet: "Veg",
        spiceLevel: 2,
        featured: false,
        popular: true,
        rating: 4.7,
        description: "Paneer cubes tossed with chunky bell peppers, onions, and freshly ground whole spices."
      },
      {
        id: "m4",
        name: "Malai Kofta",
        slug: "malai-kofta",
        category: "Curry",
        image: "/images/menu/main/malai-kofta.png",
        badge: "Luxury Choice",
        diet: "Veg",
        spiceLevel: 1,
        featured: false,
        popular: true,
        rating: 4.9,
        description: "Melt-in-the-mouth paneer dumplings dunked inside a sweet, rich cashew cream sauce."
      },
      // Breads
      {
        id: "b1",
        name: "Butter Naan",
        slug: "butter-naan",
        category: "Bread",
        image: "/images/menu/breads/butter-naan.png",
        badge: "Freshly Baked",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.8,
        description: "Traditional leavened flatbread slapped on tandoor walls and glazed with butter."
      },
      {
        id: "b2",
        name: "Garlic Naan",
        slug: "garlic-naan",
        category: "Bread",
        image: "/images/menu/breads/garlic-naan.png",
        badge: "Fan Favorite",
        diet: "Veg",
        spiceLevel: 0,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Fluffy tandoori naan topped with aromatic minced garlic and fresh cilantro."
      },
      {
        id: "b3",
        name: "Tandoori Roti",
        slug: "tandoori-roti",
        category: "Bread",
        image: "/images/menu/breads/tandoori-roti.png",
        badge: "Whole Wheat",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.7,
        description: "Rustic, wholesome whole-wheat flatbread baked cleanly over charcoal tandoor heat."
      },
      {
        id: "b4",
        name: "Lachha Paratha",
        slug: "lachha-paratha",
        category: "Bread",
        image: "/images/menu/breads/lachha-paratha.png",
        badge: "Flaky",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.8,
        description: "Multi-layered crispy whole wheat flatbread brushed with ghee."
      },
      // Rice & Biryani
      {
        id: "r1",
        name: "Veg Biryani",
        slug: "veg-biryani",
        category: "Rice",
        image: "/images/menu/rice/veg-biryani.png",
        badge: "Hyderabadi Style",
        diet: "Veg",
        spiceLevel: 2,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Long-grain basmati rice layered with spiced vegetables, saffron, and fried onions."
      },
      {
        id: "r2",
        name: "Jeera Rice",
        slug: "jeera-rice",
        category: "Rice",
        image: "/images/menu/rice/jeera-rice.png",
        badge: "Classic",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.7,
        description: "Fragrant basmati rice tempered with roasted cumin seeds and fresh ghee."
      },
      {
        id: "r3",
        name: "Veg Pulao",
        slug: "veg-pulao",
        category: "Rice",
        image: "/images/menu/rice/veg-pulao.png",
        badge: "Aromatic",
        diet: "Veg",
        spiceLevel: 1,
        featured: false,
        popular: false,
        rating: 4.6,
        description: "Basmati rice cooked with whole spices, carrots, peas, beans, and fresh herbs."
      }
    ]
  },
  {
    id: 3,
    title: "Desserts",
    key: "dessertDishes",
    icon: "CakeSlice",
    description: "Traditional Indian sweets and premium desserts.",
    dishes: [
      {
        id: "d1",
        name: "Gulab Jamun",
        slug: "gulab-jamun",
        image: "/images/menu/desserts/gulab-jamun.png",
        badge: "All-Time Favorite",
        diet: "Veg",
        spiceLevel: 0,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Soft, golden milk-solid dumplings soaked in warm rose and cardamom syrup."
      },
      {
        id: "d2",
        name: "Rasmalai",
        slug: "rasmalai",
        image: "/images/menu/desserts/rasmalai.png",
        badge: "Royal Special",
        diet: "Veg",
        spiceLevel: 0,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Soft cottage cheese patties soaked in saffron and cardamom flavored thick milk."
      },
      {
        id: "d3",
        name: "Gajar Halwa",
        slug: "gajar-halwa",
        image: "/images/menu/desserts/gajar-halwa.png",
        badge: "Seasonal",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.8,
        description: "Traditional pudding made with grated carrots, pure ghee, milk, khoya, and nuts."
      },
      {
        id: "d4",
        name: "Moong Dal Halwa",
        slug: "moong-dal-halwa",
        image: "/images/menu/desserts/moong-dal-halwa.png",
        badge: "Rich & Ghee",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: false,
        rating: 4.8,
        description: "Rich winter delicacy made by slow roasting yellow lentils in pure ghee and nuts."
      },
      {
        id: "d5",
        name: "Kesar Pista Kulfi",
        slug: "kulfi",
        image: "/images/menu/desserts/kulfi.png",
        badge: "Traditional Ice Cream",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: false,
        rating: 4.8,
        description: "Rich, dense Indian ice cream flavored with saffron, cardamom, and chopped pistachios."
      }
    ]
  },
  {
    id: 4,
    title: "Beverages",
    key: "beverageDishes",
    icon: "Coffee",
    description: "Refreshing drinks, mocktails and hot beverages.",
    dishes: [
      {
        id: "v1",
        name: "Fresh Lime Soda",
        slug: "fresh-lime-soda",
        image: "/images/menu/beverages/fresh-lime-soda.png",
        badge: "Refreshing",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.7,
        description: "Sparkling soda with freshly squeezed lime juice, available in sweet or salted options."
      },
      {
        id: "v2",
        name: "Cold Coffee",
        slug: "cold-coffee",
        image: "/images/menu/beverages/cold-coffee.png",
        badge: "Creamy",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.8,
        description: "Rich brewed espresso blended smoothly with chilled milk and chocolate syrup."
      },
      {
        id: "v3",
        name: "Mango Lassi",
        slug: "mango-lassi",
        image: "/images/menu/beverages/mango-lassi.png",
        badge: "Summer Special",
        diet: "Veg",
        spiceLevel: 0,
        featured: true,
        popular: true,
        rating: 4.9,
        description: "Thick yogurt smoothie blended with sweet mango pulp and a touch of cardamom."
      },
      {
        id: "v5",
        name: "Virgin Mojito",
        slug: "virgin-mojito",
        image: "/images/menu/beverages/virgin-mojito.png",
        badge: "Cooler",
        diet: "Veg",
        spiceLevel: 0,
        featured: false,
        popular: true,
        rating: 4.8,
        description: "Refreshing mocktail of muddled fresh mint leaves, lime juice, sugar, and sparkling soda."
      }
    ]
  }
];